#if UNITY_EDITOR
using System;
using System.Collections.Generic;

namespace FortressFrontier.Editor
{
    internal static class PresentationAssetManifest
    {
        private const string ArtRoot = "Assets/Game/Art/Formal/PNG/";
        private const string V12ArtRoot = ArtRoot + "SchemaV12/";

        public static IReadOnlyDictionary<string, string> Assets { get; } =
            new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["art.resource.food"] = ArtRoot + "icon_food.png",
                ["art.resource.meat"] = ArtRoot + "icon_meat.png",
                ["art.resource.wine"] = ArtRoot + "icon_wine.png",
                ["art.resource.wood"] = ArtRoot + "icon_wood.png",
                ["art.resource.plank"] = ArtRoot + "icon_plank.png",
                ["art.resource.raw-stone"] = ArtRoot + "icon_ore.png",
                ["art.resource.stone"] = ArtRoot + "icon_stone.png",
                ["art.resource.iron-ore"] = ArtRoot + "icon_iron.png",
                ["art.resource.iron-ingot"] = ArtRoot + "icon_ingot.png",
                ["art.resource.gold"] = ArtRoot + "icon_reward_core.png",
                ["art.boss.stone-golem"] = ArtRoot + "boss_stone_golem.png",
                ["art.research.attack"] = ArtRoot + "card_research_attack.png",
                ["art.research.defense"] = ArtRoot + "card_research_defense.png",
                ["art.research.tactics"] = ArtRoot + "card_research_tactics.png",
                ["art.research.melee"] = V12ArtRoot + "research_melee.png",
                ["art.research.ranged"] = V12ArtRoot + "research_ranged.png",
                ["art.research.magic"] = V12ArtRoot + "research_magic.png",
                ["art.research.siege"] = V12ArtRoot + "research_siege.png",
                ["art.map.prologue"] = V12ArtRoot + "map_prologue.png",
                ["art.map.river-pass"] = V12ArtRoot + "map_river_pass.png",
                ["art.worker.food.player"] = V12ArtRoot + "worker_food_friendly.png",
                ["art.worker.food.enemy"] = V12ArtRoot + "worker_food_enemy.png",
                ["art.worker.wood.player"] = V12ArtRoot + "worker_wood_friendly.png",
                ["art.worker.wood.enemy"] = V12ArtRoot + "worker_wood_enemy.png",
                ["art.worker.stone.player"] = V12ArtRoot + "worker_stone_friendly.png",
                ["art.worker.stone.enemy"] = V12ArtRoot + "worker_stone_enemy.png",
                ["art.worker.iron.player"] = V12ArtRoot + "worker_iron_friendly.png",
                ["art.worker.iron.enemy"] = V12ArtRoot + "worker_iron_enemy.png",
                ["art.unit.gatherer"] = V12ArtRoot + "worker_food_friendly.png",
                ["art.unit.lumberjack"] = V12ArtRoot + "worker_wood_friendly.png",
                ["art.unit.stonecutter"] = V12ArtRoot + "worker_stone_friendly.png",
                ["art.unit.iron-miner"] = V12ArtRoot + "worker_iron_friendly.png",
                ["art.unit.builder"] = ArtRoot + "unit_builder_friendly.png",
                ["art.unit.shield-guard"] = ArtRoot + "unit_shield_soldier_friendly.png",
                ["art.unit.archer"] = ArtRoot + "unit_archer_friendly.png",
                ["art.unit.siege-ram"] = ArtRoot + "unit_siege_ram_friendly.png",
                ["art.unit.heavy-warrior"] = V12ArtRoot + "unit_heavy_warrior_friendly.png",
                ["art.unit.mage"] = V12ArtRoot + "unit_mage_friendly.png",
                ["art.unit.longbow"] = V12ArtRoot + "unit_longbow_friendly.png",
                ["art.unit.cannon"] = V12ArtRoot + "unit_cannon_cart_friendly.png",
                ["art.building.pasture"] = ArtRoot + "building_farm.png",
                ["art.building.winery"] = ArtRoot + "building_farm.png",
                ["art.building.sawmill"] = ArtRoot + "building_sawmill.png",
                ["art.building.stoneworks"] = ArtRoot + "building_quarry.png",
                ["art.building.iron-smelter"] = ArtRoot + "building_engineer_yard.png",
                ["art.building.warehouse"] = ArtRoot + "building_lumber_camp.png",
                ["art.building.shield-camp"] = ArtRoot + "building_shield_camp.png",
                ["art.building.archer-camp"] = ArtRoot + "building_archer_range.png",
                ["art.building.ram-camp"] = ArtRoot + "building_barracks.png",
                ["art.building.heavy-warrior-camp"] = V12ArtRoot + "building_heavy_warrior_camp.png",
                ["art.building.mage-camp"] = V12ArtRoot + "building_mage_camp.png",
                ["art.building.longbow-camp"] = V12ArtRoot + "building_longbow_camp.png",
                ["art.building.cannon-camp"] = V12ArtRoot + "building_cannon_camp.png",
                ["art.building.research-lab"] = ArtRoot + "building_engineer_yard.png",
                ["art.building.arrow-tower"] = ArtRoot + "building_arrow_tower_friendly.png",
                ["art.building.gatherer-lodge"] = V12ArtRoot + "building_food_gatherer_camp.png",
                ["art.building.wood-gatherer-camp"] = V12ArtRoot + "building_wood_gatherer_camp.png",
                ["art.building.stone-gatherer-camp"] = V12ArtRoot + "building_stone_gatherer_camp.png",
                ["art.building.iron-gatherer-camp"] = V12ArtRoot + "building_iron_gatherer_camp.png",
                ["art.card.building.pasture"] = ArtRoot + "building_farm.png",
                ["art.card.building.winery"] = ArtRoot + "building_farm.png",
                ["art.card.building.sawmill"] = ArtRoot + "building_sawmill.png",
                ["art.card.building.stoneworks"] = ArtRoot + "building_quarry.png",
                ["art.card.building.iron-smelter"] = ArtRoot + "building_engineer_yard.png",
                ["art.card.building.warehouse"] = ArtRoot + "building_lumber_camp.png",
                ["art.card.building.shield-camp"] = ArtRoot + "building_shield_camp.png",
                ["art.card.building.archer-camp"] = ArtRoot + "building_archer_range.png",
                ["art.card.building.ram-camp"] = ArtRoot + "building_barracks.png",
                ["art.card.building.heavy-warrior-camp"] = V12ArtRoot + "building_heavy_warrior_camp.png",
                ["art.card.building.mage-camp"] = V12ArtRoot + "building_mage_camp.png",
                ["art.card.building.longbow-camp"] = V12ArtRoot + "building_longbow_camp.png",
                ["art.card.building.cannon-camp"] = V12ArtRoot + "building_cannon_camp.png",
                ["art.card.building.research-lab"] = ArtRoot + "building_engineer_yard.png",
                ["art.card.building.gatherer-lodge"] = V12ArtRoot + "building_food_gatherer_camp.png",
                ["art.card.building.wood-gatherer-camp"] = V12ArtRoot + "building_wood_gatherer_camp.png",
                ["art.card.building.stone-gatherer-camp"] = V12ArtRoot + "building_stone_gatherer_camp.png",
                ["art.card.building.iron-gatherer-camp"] = V12ArtRoot + "building_iron_gatherer_camp.png",
                ["art.card.battlefield.arrow-tower"] = ArtRoot + "card_arrow_tower.png",
                ["art.card.tactic.field-rations"] = ArtRoot + "card_field_rations.png",
                ["art.card.tactic.emergency-supplies"] = ArtRoot + "card_emergency_supplies.png",
                ["art.card.tactic.arrow-rain"] = ArtRoot + "card_arrow_rain.png",
                ["art.card.soldier.shield-guard"] = ArtRoot + "unit_shield_soldier_friendly.png",
                ["art.card.soldier.archer"] = ArtRoot + "unit_archer_friendly.png",
                ["art.card.soldier.siege-ram"] = ArtRoot + "unit_siege_ram_friendly.png",
                ["art.card.soldier.heavy-warrior"] = V12ArtRoot + "unit_heavy_warrior_friendly.png",
                ["art.card.soldier.mage"] = V12ArtRoot + "unit_mage_friendly.png",
                ["art.card.soldier.longbow"] = V12ArtRoot + "unit_longbow_friendly.png",
                ["art.card.soldier.cannon"] = V12ArtRoot + "unit_cannon_cart_friendly.png"
            };
    }
}
#endif
